#!/usr/bin/bash

# Testa recebimento de parametros

if [ $# -eq 0 ]
then
    echo "Falta nome do arquivo a ser tratado"
fi

# Funcao auxiliar para validar endereco IP
function valida_ip()
{
    local endip=$1
    local resp=1

    if [[ $endip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; 
    then
        sep=$IFS
        IFS='.'
        endip=($endip)
        IFS=$sep
        if [[ ${endip[0]} -le 255 && ${endip[1]} -le 255 && ${endip[2]} -le 255 && ${endip[3]} -le 255 ]];
        then 
            resp=$?
        fi
    fi
    echo $resp
    return $resp
}

# Funcao auxiliar para procurar itens dentro de um array

function contem() 
{
    local n=$#
    local v=${!n}
    for ((i=1;i < $#;i++)) 
    {
        if [ "${!i}" == "${v}" ]; 
        then
            echo "1"
            return 0
        fi
    }
    echo "0"
    return 1
}

# Variavel de controle dos ips
ips=()

while IFS= read -r linha
do
  # Limpa caracteres estranhos
  c0=${linha/	/ }A
  # Identifica primeira coluna
  c1=${c0%% *}
  # Tratamento linha a linha
  case $c1 in
  '#'|'') echo $linha ;;
  *) if [ $(valida_ip "$c1") == "0" ];
     then
        echo $linha
     else
     if [ $(contem "${ips[@]}" "$c1") == "0" ]; 
     then
        ips+=($c1)
        echo $linha
     fi
     fi
     ;;
  esac
done < $1
